repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        files: "^(?!examples/)"
        args: ["--application-directories", "src"]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: fix-encoding-pragma
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: system
        entry: autoflake --in-place
        args: ['--remove-all-unused-imports', '--exclude', '**/__init__.py,__init__.py']
        files: \.py$
      - id: prospector
        name: prospector
        language: system
        entry: prospector
        args: ["--profile", "./prospector.yml"]
        additional_dependencies: ["bandit>=1.5.1", "frosted>=1.4.1", "vulture>=1.5", "pyroma>=2.4"]
        pass_filenames: false
